name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: hello
      env:
        GITHUB_USER: ${{ secrets.USER }}
        GITHUB_PASSWORD: ${{ secrets.PASSWORD }}
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
      run: ./test.sh
