name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: hello
      env:
        GITHUB_TOKEN: ${{ secrets.PASSWORD }}
      run: ./test.sh
